### PR TITLE
Add zoom for Optifine

### PR DESCRIPTION
**Pull request by HongyiMC**

### CODE REVIEW

**Comment by khanhduytran0** [comment]
Where is the button located?

**Comment by khanhduytran0** [comment]
Also, you are missing 
```c
ADD_BUTTON_DEF_KEY(c, GLFW_KEY_C)
```

**Comment by HongyiMC** [comment]
> Where is the button located?

I was thinking maybe add it next to the TAB key

**Comment by khanhduytran0** [comment]
> > Where is the button located?
> 
> I was thinking maybe add it next to the TAB key

`CGRectMake(5 * 5 + 80 * 3, 5, BTN_RECT)`
B922FB79-458D-46A2-A483-0F0F0DBCBACD

**Comment by HongyiMC** [comment]
Hmmm why does it do that?

**Comment by khanhduytran0** [comment]
Because of wrong location.. it should be
```
CGRectMake(5 * 5 + 80 * 4, 5, BTN_RECT)
                        ^ here
```

**Pull request merged**
